apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pull-request
  title: Pull Request Action template
  description: scaffolder v1beta3 template demo publishing to PR on existing git repository
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    $yaml: ../../defaults/parameters/app-onboard.yaml


  steps:
    $yaml: ../../defaults/steps/fetch-publish.yaml


  output:
    links:
      - url: ${{steps.publish.output.mergeRequestUrl}}ßß
        title: "Go to PR"