apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: pull-request
  title: Pull Request Action template
  description: scaffolder v1beta3 template demo publishing to PR on existing git repository
spec:
  owner: backstage/techdocs-core
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - name
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Description of the component
        targetPath:
          title: Target Path in repo
          type: string
          description: Name of the directory to create in the repository
        dockerfile:
          title: Include Dockerfile
          type: boolean
    - title: Choose a location
      required:
        - repo
      properties:
        repo:
          title: Repository Location
          type: object
          properties:
            host:
              title: Repo Host
              type: string
              description: Your SCM host
              default: gitlab-gitlab.apps.cluster-lqhhl.sandbox3194.opentlc.com
              enum:
                - gitlab-gitlab.apps.cluster-lqhhl.sandbox3194.opentlc.com
            owner:
              title: Repo Owner
              type: string
              description: Your SCM host organization/group
              default: development
              enum:
                - development
            name:
              title: Repo Name
              type: string
              description: Your SCM host name


  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          name: ${{parameters.name}}
        targetPath: ./workspace

    - id: fetch-dockerfile
      name: Fetch Dockerfile
      if: ${{ parameters.dockerfile }}
      action: fetch:template
      input:
        url: ./dockerfile
        targetPath: ./workspace

    - id: publish
      name: Publish
      action: publish:gitlab:merge-request
      input:
        sourcePath: ./workspace
        repoUrl: ${{parameters.repo.host}}?repo=${{parameters.repo.name}}&owner=${{parameters.repo.owner}}
        title: "Create new project: ${{parameters.name}}"
        branchName: create-${{parameters.name}}
        description: |
          # New project: ${{parameters.name}}

          ${{ parameters.description if parameters.description }}
        targetPath: ${{ parameters.targetPath if parameters.targetPath else parameters.name }}

  output:
    links:
      - url: ${{steps.publish.output.mergeRequestUrl}}
        title: "Go to PR"